development:
  auth0_domain: ENV['auth0_domain']
  auth0_client_id: ENV['auth0_client_id']
  auth0_client_secret: ENV['auth0_client_secret']

test:
  auth0_domain: ENV['auth0_domain']
  auth0_client_id: ENV['auth0_client_id']
  auth0_client_secret: ENV['auth0_client_secret']